// Generated by Haxe 4.3.1
(function ($global) { "use strict";
var ArrayCounter = function() { };
ArrayCounter.main = function() {
	var _g = [];
	var _g1 = 0;
	while(_g1 < 100) {
		var i = _g1++;
		if(i % 2 == 0) {
			_g.push(i);
		}
	}
	var evenNumber = _g;
	var _g = 0;
	while(_g < evenNumber.length) {
		var num = evenNumber[_g];
		++_g;
		console.log("ArrayCounter.hx:6:",num);
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
ArrayCounter.main();
})({});
