// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
public class AnonymousTypes : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		global::AnonymousTypes.main();
	}
	public AnonymousTypes(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public AnonymousTypes() {
		global::AnonymousTypes.__hx_ctor__AnonymousTypes(this);
	}
	
	
	protected static void __hx_ctor__AnonymousTypes(global::AnonymousTypes __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			object point = new global::haxe.lang.DynamicObject(new int[]{}, new object[]{}, new int[]{120, 121}, new double[]{((double) (10) ), ((double) (15) )});
			{
				object __temp_dynop1 = point;
				int __temp_expr1 = ((int) (global::haxe.lang.Runtime.setField_f(__temp_dynop1, "x", 120, ((double) (( ((int) (global::haxe.lang.Runtime.getField_f(__temp_dynop1, "x", 120, true)) ) + 5 )) ))) );
			}
			
			global::haxe.Log.trace.__hx_invoke2_o(default(double), point, default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"main", "AnonymousTypes", "AnonymousTypes.hx"}, new int[]{1981972957}, new double[]{((double) (6) )}));
		}
	}
	
	
}


